export const starships = [
    {
        id: 'enterprise-a',
        shipName: 'Constitution refit Enterprise-A',
        shipImage: 'Constitution-refit-Enterprise-A.jpg',
        shipDescription: 'This, very old model has been heavily modified for modern usage. There are modifications to the deflector dish, the side walls of the engineering hull, the nacelle spires, the nacelle aft ends and the bridge module. The crew capacity has been increased from 200 to 400 crew members without forsaking comfort. The completely new bridge module has all the newest features an intrepid captain may want.',
        shipCategory: 'Constitution class.',
        shipPrice: 2,
    },
    {
        id: 'enterprise-b',
        shipName: 'Excelsior-class Enterprise-B',
        shipImage: 'Excelsior-class-Enterprise-B.jpg',
        shipDescription: 'The Excelsior-class was a type of Federation starship used by Starfleet from the late 23rd century through the late 24th century. It was the backbone of Starfleet for nearly a century, making it one of the longest serving starship designs, and one of the most recognizable ships in the fleet. You will not regret a purchase like this.',
        shipCategory: 'Excelsior class.',
        shipPrice: 3,
    },
    {
        id: 'enterprise-c',
        shipName: 'Ambassador-class Enterprise-C',
        shipImage: 'Ambassador-class-Enterprise-C.jpg',
        shipDescription: 'The Ambassador-class features the saucer section-engineering section-warp nacelle layout common to most Starfleet vessels. It is intermediate in size between the Excelsior-class and the Galaxy-class. In addition, the ship boasts at least three engineering levels for all your science needs!',
        shipCategory: 'Ambassador class.',
        shipPrice: 6,
    },
    {
        id: 'daedalus',
        shipName: 'USS Daedalus',
        shipImage: 'USS-Daedalus.jpg',
        shipDescription: 'The Daedalus may be old, but you can rely on this ship, especially for the cost. The Daedalus-class was an early class of Starfleet vessel that, unlike most Federation starship designs, was designed with a spherical primary hull, outwardly similar to the later Olympic-class. This ship, which operated with a crew of approximately 229, was decommissioned by the year 2196. If you do ever find yourself and your crew stranded, it had a unique subspace distress call sure to attract friends to help you out!',
        shipCategory: 'Antiquated space junk.',
        shipPrice: 1,
    },
    {
        id: 'honshu',
        shipName: 'Nebula-Class USS Honshu',
        shipImage: 'Nebula-Class-USS-Honshu.jpg',
        shipDescription: 'The Nebula-class shares a similar design lineage with its larger Galaxy-class counterpart, notably its primary and secondary hulls and nacelles. Atop the primary hull is a superstructure which can support a variety of modules, such as the inclusion of a triangular platform, fitted with torpedo launchers, an oval platform, or additional warp nacelles.',
        shipCategory: 'Nebula class.',
        shipPrice: 4,
    },
    {
        id: 'reliant',
        shipName: 'Miranda-class Reliant',
        shipImage: 'Miranda-class-Reliant.jpg',
        shipDescription: 'The configuration of the Miranda-class shares a similar design lineage and features with our refitted Constitution-class. The Miranda-class is composed of a single primary hull, consisting of a saucer that is similar to that of the Constitution-class; however, the bridge module, positioned on top in the center, is shaped differently than the Constitution-class module.',
        shipCategory: 'Miranda class.',
        shipPrice: 5,
    }
];